cmake_minimum_required(VERSION 2.8)
project(Pluto)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}  -std=c++11")
add_subdirectory(SinglePhasing)
add_subdirectory(pbwtWrapper)
LINK_DIRECTORIES(/net/wonderland/home/fanzhang/WorkingSpace/lib)
#LINK_DIRECTORIES(/Users/fanzhang/BioLib/lib)
set(SOURCE_FILES main.cpp)
add_executable(Pluto ${SOURCE_FILES})
target_link_libraries(Pluto  PBWTWrapper thunderVCF)
